### ISSUE TITLE
Allow configurable shared lib location

### ISSUE THREAD

**Issue by fosskers** [garlic0x1/cl-webui#2]
Arch Linux has a `webui` package in the AUR, but it installs its `.so` to:
```
/usr/lib/libwebui.so
```
which is not what this wrapper looks for. It would be convenient if this could somehow be configured.

**Comment by garlic0x1** [comment]
@fosskers This should work, assuming `libwebui.so` and `webui-2.so` are the same.
https://github.com/garlic0x1/cl-webui/commit/effdc424a6fb9eb9a122b628af1e41ead2874855

**Comment by fosskers** [comment]
This seems to work, as least as far as linking is concerned. Thank you!
